### ISSUE TITLE
Failed to load plugins.diagram

### ISSUE THREAD

**Issue by mixtli** [3rd/diagram.nvim#1]
After installing in lazy using the provided config and restarting my editor:

Error detected while processing /Users/mixtli/dotfiles/config/nvim/init.lua:
Failed to load `plugins.diagram`

/Users/mixtli/.config/nvim/lua/plugins/diagram.lua:14: module 'diagram.integrations.markdown' not found:
^Ino field package.preload['diagram.integrations.markdown']
cache_loader: module diagram.integrations.markdown not found
cache_loader_lib: module diagram.integrations.markdown not found
^Ino file './diagram/integrations/markdown.lua'
^Ino file '/opt/homebrew/share/luajit-2.1/diagram/integrations/markdown.lua'
^Ino file '/usr/local/share/lua/5.1/diagram/integrations/markdown.lua'
^Ino file '/usr/local/share/lua/5.1/diagram/integrations/markdown/init.lua'
^Ino file '/opt/homebrew/share/lua/5.1/diagram/integrations/markdown.lua'
^Ino file '/opt/homebrew/share/lua/5.1/diagram/integrations/markdown/init.lua'
^Ino file './diagram/integrations/markdown.so'
^Ino file '/usr/local/lib/lua/5.1/diagram/integrations/markdown.so'
^Ino file '/opt/homebrew/lib/lua/5.1/diagram/integrations/markdown.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
^Ino file './diagram.so'
^Ino file '/usr/local/lib/lua/5.1/diagram.so'
^Ino file '/opt/homebrew/lib/lua/5.1/diagram.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'

# stacktrace:
  - ~/.config/nvim/lua/plugins/diagram.lua:14 _in_ **load**
  - ~/.config/nvim/lua/user/plugins.lua:15
  - nvim/init.lua:13

**Comment by raguay** [comment]
I'm getting the same error.

**Comment by 3rd** [comment]
Hey, I should've left that part out, please remove this and it should work:

```lua
integrations = {
      require("diagram.integrations.markdown"),
    },
```

In your case the require runs before your plugin manager adds it to rtp.

**Comment by raguay** [comment]
That worked for me. Thanks.
