### ISSUE TITLE
All images hidden entering insert mode, only diagram restored returning to normal mode

### ISSUE THREAD

**Issue by cpb** [3rd/diagram.nvim#4]
Here's a short clip demonstrating the issue I experienced.

1. A markdown document including:
    ``````
    ![lorem picsum](https://picsum.photos/500/500)

    ```mermaid
    graph LR
      A --> B
    ```
    ``````
2. Enter insert mode, observe all images disappear
3. Exit insert mode, observe only diagrams reappear

The video replaces the `A` with `B` bet the result is the same.

https://github.com/user-attachments/assets/97e0ea10-0552-4285-ba76-9678ecfe02e6

**Comment by 3rd** [comment]
Hey, thank you for the issue, it should be fixed now!

**Comment by cpb** [comment]
Thank you, https://github.com/3rd/diagram.nvim/commit/6bbc2b04dd67960c01c7984d08c89d847a630074 fixes it for me!
